version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "widen"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
